#!/bin/bash

# I made sure to prefix all the Pis in the tower with rpi4
function allpis {
  grep "rpi4" /etc/hosts | awk '{print $2}'
}

function distribute {
  echo "Distributing resources..."
  FILES=$@
  for file in $FILES
  do
    for pi in $(allpis)
    do
      scp $file pi@${pi}:$file
    done
  done
}

function fallback {
  echo "Fallin back troops..."

  for pi in $(allpis)
  do
    ssh $pi 'hostname; reboot; echo'
  done
}

function fortify {
  echo "Fortifying fortress..."

  for pi in $(allpis)
  do
    ssh $pi 'hostname; sudo apt-get update; echo'
  done
}

function quality {
  echo "Checking perimeter..."

  for pi in $(allpis)
  do
    ssh $pi 'hostname; vcgencmd measure_temp; java -version; echo'
  done
}

function steady {
  echo "Steadying the lines... $@"

  for pi in $(allpis)
  do
    ssh $pi "$@"
  done
}

COMMAND=$1

case $COMMAND in
  distribute | dist)
    distribute ${@:2};;
  fallback | fall)
    fallback;;
  fortify | fort)
    fortify;;
  steady | st)
    steady ${@:2};;
  quality | q)
    quality;;
  *)
    echo "Command unrecognized. Try the following instead:"
    echo "distribute <filename> - to scp files to all units"
    echo "fallback - to reboot all units"
    echo "fortify - to update all units"
    echo "steady - to install packages to all units"
    echo "quality - to get the temp of all units"
    ;;
esac
