#!/bin/bash

# I made sure to prefix all the Pis in the tower with rpi4
function allpis {
  grep "rpi4" /etc/hosts | awk '{print $2}'
}

function distribute () {
  for FILENAME in "$@"
  do
    for pi in $(allpis)
    do
      scp $FILENAME pi@${pi}:$FILENAME
    done
  done
}

function fallback () {
  echo "Fallin back troops..."

  for pi in $(allpis)
  do
    ssh pi@${pi} 'hostname; reboot; echo'
  done
}

function fortify () {
  echo "Fortifying fortress..."

  for pi in $(allpis)
  do
    ssh pi@${pi} 'hostname; sudo apt-get update; echo'
  done
}

function steady () {
  echo "Steadying the lines..."

  for pi in $(allpis)
  do
    ssh pi@${pi} 'hostname; sudo apt-get install dnsutils ufw; echo'
  done
}

function quality () {
  echo "Checking fortress..."

  for pi in $(allpis)
  do
    ssh pi@${pi} 'hostname; vcgencmd measure_temp; java -version; echo'
  done
}

COMMAND=$1

case $COMMAND in
  distribute | dist)
    distribute;;
  fallback | fall)
    fallback;;
  fortify | fort)
    fortify;;
  steady | st)
    steady;;
  quality | q)
    quality;;
  *)
    echo "Command unrecognized. Try the following instead:"
    echo "distribute <filename> - to scp files to all units"
    echo "fallback - to reboot all units"
    echo "fortify - to update all units"
    echo "steady - to install packages to all units"
    echo "quality - to get the temp of all units"
    ;;
esac
